backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/public/cms/images"

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio List" # Used in the UI
    folder: "/public/cms/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Image", name: "thumbnail", widget: "image"}
      - label: "Preview Images"
        name: "previews" 
        widget: "list"
        field:
          - {label: "Image", name: "image", Widget: "image"}
          - {label: "Desc", name: "desc", Widget: "string"}

extension: "json"
format: "json"